YAML batch_2 update
eurodatacube/eodash-catalog pull request #101
Opened 2024-02-23 14:08 UTC by FedericoRondoni

E10a1_agricultural_production_productive_area E10a2_agricultural_production_area E10a3_agricultural_production_area_change E10a10_harvesting_evolution E10a5_fruit_production E10a6_harvested_parcels_evolution E10a8_winter_cereals E10a9_agricultural_workers E11_shopping_center_activity

2024-02-23 15:40 UTC, santilland commented
Strange, locally it seems to run fine, might be a connection issue to one of the services, i will try to rerun

2024-02-23 15:44 UTC, santilland commented
seems to throw always the same error, searching a bit for potential issues i found:
Windows style newline characters can cause issues in Cygwin
I will try to check the new line format in the file

2024-02-23 15:54 UTC, santilland commented
@FedericoRondoni could you push another small change? Is it possible you had a line break in the pull request first comment before?
If yes, maybe your edit fixed it, if not, i can't really think of why it is not working. The build works fine locally.

2024-02-26 10:01 UTC, FedericoRondoni commented
@santilland yes, it might be that. How can we solve it?

2024-02-26 11:01 UTC, lubojr commented
@FedericoRondoni I'm afraid that after you've edited the PR comment, you need to push a new commit (with some, even tiny changes) to trigger the automatic workflow with the new PR comment applied.

For us rerunning a past workflow would take the PR comment in the original form in the past.

2024-02-27 10:42 UTC, FedericoRondoni commented
Hi @santilland and @lubojr now it worked 😊 
Thanks!

2024-03-14 09:03 UTC, FedericoRondoni commented
@dmoglioni

2024-03-26 14:07 UTC, aapopescu commented on collections/E10a10_harvesting_evolution.yaml
> +  - Name: Copernicus
actually this indicator is provided by VISTA in a study finded by ESA:
The study is [“Impact of COVID-19 on Harvest of Row Crops”](https://eo4society.esa.int/projects/impact-of-covid-19-on-harvest-of-row-crop/) conducted by [VISTA Remote Sensing in Geosciences GmbH] and funded by the European Space Agency.

2024-03-26 14:57 UTC, aapopescu commented on collections/E10a1_agricultural_production_productive_area.yaml
> -    - Name: FAO
@FedericoRondoni , this indicator was produced by UCL https://uclouvain.be/en/index.html, please update provider.

2024-03-26 15:19 UTC, aapopescu commented on collections/E10a3_agricultural_production_area_change.yaml
> -    - Name: FAO
@FedericoRondoni provider is UCL, same comment as for E10a2

2024-03-26 15:19 UTC, aapopescu commented on collections/E10a2_agricultural_production_area.yaml
> -    - Name: FAO
@FedericoRondoni , provider is UCL, same comment as in E10a1

2024-04-02 08:37 UTC, aapopescu commented on collections/E10a5_fruit_production.yaml
> +Provider:
Provider of the dataset is UCL https://uclouvain.be/en/index.html

2024-04-02 11:34 UTC, aapopescu commented on collections/E11_shopping_center_activity.yaml
> +Provider:
Indicator provided by Sistema https://sistema.at/

2024-04-02 12:14 UTC, aapopescu requested changes
@FedericoRondoni please address the comments in the yamls

2024-04-02 14:50 UTC, FedericoRondoni commented
> @FedericoRondoni please address the comments in the yamls

I think I have done it. I'm not sure I know how to handle a change request in GitHub, but the files should be good now

2024-04-09 07:33 UTC, merged