Update C1_ports_shipping_aq.yaml
eurodatacube/eodash-catalog pull request #84
Opened 2024-01-25 14:22 UTC by FedericoRondoni

Test to understand if the nested DataSource element can be used for the YAML files + integration of the new References element inside the YAML

2024-02-16 15:31 UTC, FedericoRondoni commented
Hi @santilland @lubojr 
I don't know if I'm doing something wrong. I tried to modify the YAML files directly from here as we agreed, but I see that "all checks have failed". I don't know what these checks are.
Please tell me if I have to do something different :)

2024-02-16 15:43 UTC, FedericoRondoni commented
Hi @santilland and thanks for your reply. How can I do that?

2024-02-16 15:52 UTC, santilland commented
You can write the list of collection identifiers (separated by spaces) you want to test in the body of the pull request. So by editing the first "comment" of the pull request. After you push a commit it should then only generate the collections provided in that list.

2024-02-16 16:06 UTC, FedericoRondoni commented
Like this?
Sorry for these questions, but I'm not an expert GitHub user

2024-02-16 16:11 UTC, santilland commented
No problem, it is not common use what we are doing here, so questions are very much welcome, we will need to better describe and document the process we are still evaluating.
The collection identifier for generation is the file name (without the extension), so in this case it would be:

C1_ports_shipping_aq CDS3_wind_10m_u

2024-02-16 16:26 UTC, FedericoRondoni commented
Ah ok! Clear
Thanks Daniel

2024-02-16 16:30 UTC, santilland commented
Looks good, this should apply for your next commit then

2024-02-21 12:48 UTC, santilland commented
@FedericoRondoni please make sure that the license field uses a spdx license identifier as defined here:
https://spdx.org/licenses/

2024-02-21 13:29 UTC, FedericoRondoni commented
> @FedericoRondoni please make sure that the license field uses a spdx license identifier as defined here: https://spdx.org/licenses/

Hi Daniel, I checked already, but I couldn't find any relevant license. I will check again.
However, is there a procedure to bypass this issue if one license is not present in the spdx catalogue?

2024-02-23 13:03 UTC, FedericoRondoni commented
Hi @santilland, I also added the license field to two yaml files here, but maybe there is something that you need to implement in this branch as well?

2024-02-23 13:06 UTC, santilland commented
Yes, we will need to merge the updates from the other branch to this one, i can do it once we merge the other branch

2024-02-23 13:13 UTC, FedericoRondoni commented
> Yes, we will need to merge the updates from the other branch to this one, i can do it once we merge the other branch

Ok perfect!

2024-02-29 15:52 UTC, FedericoRondoni commented
Hi guys @santilland @lubojr once the merging of the assets branch YAML-alignment is done, we can ask Anca to review these YAMLs and descriptions.
We will continue to prepare the other batches.

2024-03-04 08:31 UTC, santilland commented
@aapopescu this pull request is the first batch ready to be merged, you can see the preview of the catalog with following url:
https://eodash-testing.eox.at/ui-panels-cat-stacinfo/?catalog=yaml_test

2024-03-13 14:48 UTC, aapopescu commented on collections/C3_ports_people_aq.yaml
where is the Subtitle used?

2024-03-13 14:48 UTC, aapopescu commented on collections/CDS1_temperature.yaml
cannot find this indicator on the test URL

2024-03-13 14:48 UTC, aapopescu commented on collections/CDS1_temperature.yaml
Why does this indicator have an additional Attribute "Name"?

2024-03-13 14:53 UTC, aapopescu commented on collections/E13o_vessel_density_all.yaml
rename to "Vessel Density - all types of ships"

2024-03-13 14:54 UTC, aapopescu commented on collections/E13o_vessel_density_all.yaml
can we group all EMODNET indicators into a single one?

2024-03-13 14:54 UTC, aapopescu commented on collections/C3_ports_people_aq.yaml
can we group all three indicators into a single one?

2024-03-13 14:55 UTC, santilland commented on collections/C3_ports_people_aq.yaml
We are current not displaying it in the dashboard, i thought while doing data sanitation it might be an interesting attribute to have if we ever decide to include it

2024-03-13 14:59 UTC, santilland commented on collections/CDS1_temperature.yaml
It seems it is not added in the pull request description for it to be generated, will recheck

2024-03-14 15:35 UTC, FedericoRondoni commented on collections/CDS1_temperature.yaml
Sorry, you are right. Now it should be ok

2024-03-22 10:46 UTC, santilland commented
@FedericoRondoni @aapopescu the new stac structure was introduced and merged into this branch, we also merged the test branch of the client, so you can explore the client with the current data here:
https://eodash-testing.eox.at/ui-panels-cat/?catalog=yaml_test
I will write an extra mail with information on "grouping".

2024-04-08 12:29 UTC, lubojr requested changes
adapt RACE.yaml to file renamings

2024-04-08 12:50 UTC, lubojr reviewed
Ah nevermind, it is already done in this PR, sorry. It was just the issue in batch_3, batch_4, and batch_5

2024-04-08 12:50 UTC, lubojr approved these changes

2024-04-09 07:32 UTC, merged